name: Automazione Bot Sconti

# 1. QUANDO DEVE PARTIRE?
on:
  schedule:
    - cron: '0 16 * * *' # Si attiva ogni giorno alle 16:00 UTC (le 18:00 in Italia)
  workflow_dispatch: # Questo ci crea un bottone magico per farlo partire a mano quando vogliamo testarlo

# 2. COSA DEVE FARE?
jobs:
  esegui-bot:
    runs-on: ubuntu-latest # Usa un computer virtuale gratuito basato su Linux

    steps:
    - name: 📥 Scarica i file della repository
      uses: actions/checkout@v4

    - name: 🐍 Installa Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 📦 Installa gli attrezzi necessari (requests)
      run: pip install requests

    - name: 🚀 Fai partire il Bot!
      env:
        # Qui diciamo a GitHub di tirare fuori le chiavi dalla cassaforte e darle a Python
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python bot.py
